// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	service "github.com/walkline/ToCloud9/apps/charserver/service"
)

// FriendsService is an autogenerated mock type for the FriendsService type
type FriendsService struct {
	mock.Mock
}

// AddFriend provides a mock function with given fields: ctx, realmID, playerGUID, friendGUID, friendName, note
func (_m *FriendsService) AddFriend(ctx context.Context, realmID uint32, playerGUID uint64, friendGUID uint64, friendName string, note string) (*service.AddFriendResult, error) {
	ret := _m.Called(ctx, realmID, playerGUID, friendGUID, friendName, note)

	if len(ret) == 0 {
		panic("no return value specified for AddFriend")
	}

	var r0 *service.AddFriendResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, uint64, string, string) (*service.AddFriendResult, error)); ok {
		return rf(ctx, realmID, playerGUID, friendGUID, friendName, note)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, uint64, string, string) *service.AddFriendResult); ok {
		r0 = rf(ctx, realmID, playerGUID, friendGUID, friendName, note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AddFriendResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint64, uint64, string, string) error); ok {
		r1 = rf(ctx, realmID, playerGUID, friendGUID, friendName, note)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddIgnore provides a mock function with given fields: ctx, realmID, playerGUID, ignoredGUID
func (_m *FriendsService) AddIgnore(ctx context.Context, realmID uint32, playerGUID uint64, ignoredGUID uint64) (uint32, error) {
	ret := _m.Called(ctx, realmID, playerGUID, ignoredGUID)

	if len(ret) == 0 {
		panic("no return value specified for AddIgnore")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, uint64) (uint32, error)); ok {
		return rf(ctx, realmID, playerGUID, ignoredGUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, uint64) uint32); ok {
		r0 = rf(ctx, realmID, playerGUID, ignoredGUID)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint64, uint64) error); ok {
		r1 = rf(ctx, realmID, playerGUID, ignoredGUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFriendsList provides a mock function with given fields: ctx, realmID, playerGUID
func (_m *FriendsService) GetFriendsList(ctx context.Context, realmID uint32, playerGUID uint64) (*service.FriendsList, error) {
	ret := _m.Called(ctx, realmID, playerGUID)

	if len(ret) == 0 {
		panic("no return value specified for GetFriendsList")
	}

	var r0 *service.FriendsList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64) (*service.FriendsList, error)); ok {
		return rf(ctx, realmID, playerGUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64) *service.FriendsList); ok {
		r0 = rf(ctx, realmID, playerGUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.FriendsList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint64) error); ok {
		r1 = rf(ctx, realmID, playerGUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotifyStatusChange provides a mock function with given fields: ctx, realmID, playerGUID, status, area, level, classID
func (_m *FriendsService) NotifyStatusChange(ctx context.Context, realmID uint32, playerGUID uint64, status uint8, area uint32, level uint32, classID uint32) error {
	ret := _m.Called(ctx, realmID, playerGUID, status, area, level, classID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyStatusChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, uint8, uint32, uint32, uint32) error); ok {
		r0 = rf(ctx, realmID, playerGUID, status, area, level, classID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveFriend provides a mock function with given fields: ctx, realmID, playerGUID, friendGUID
func (_m *FriendsService) RemoveFriend(ctx context.Context, realmID uint32, playerGUID uint64, friendGUID uint64) error {
	ret := _m.Called(ctx, realmID, playerGUID, friendGUID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFriend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, uint64) error); ok {
		r0 = rf(ctx, realmID, playerGUID, friendGUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveIgnore provides a mock function with given fields: ctx, realmID, playerGUID, ignoredGUID
func (_m *FriendsService) RemoveIgnore(ctx context.Context, realmID uint32, playerGUID uint64, ignoredGUID uint64) error {
	ret := _m.Called(ctx, realmID, playerGUID, ignoredGUID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveIgnore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, uint64) error); ok {
		r0 = rf(ctx, realmID, playerGUID, ignoredGUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetFriendNote provides a mock function with given fields: ctx, realmID, playerGUID, friendGUID, note
func (_m *FriendsService) SetFriendNote(ctx context.Context, realmID uint32, playerGUID uint64, friendGUID uint64, note string) error {
	ret := _m.Called(ctx, realmID, playerGUID, friendGUID, note)

	if len(ret) == 0 {
		panic("no return value specified for SetFriendNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint64, uint64, string) error); ok {
		r0 = rf(ctx, realmID, playerGUID, friendGUID, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFriendsService creates a new instance of FriendsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendsService {
	mock := &FriendsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
