// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	events "github.com/walkline/ToCloud9/shared/events"

	service "github.com/walkline/ToCloud9/apps/charserver/service"
)

// OnlinePlayersCache is an autogenerated mock type for the OnlinePlayersCache type
type OnlinePlayersCache struct {
	mock.Mock
}

// GetOnlineInfo provides a mock function with given fields: playerGUID
func (_m *OnlinePlayersCache) GetOnlineInfo(playerGUID uint64) (service.OnlinePlayerInfo, bool) {
	ret := _m.Called(playerGUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOnlineInfo")
	}

	var r0 service.OnlinePlayerInfo
	var r1 bool
	if rf, ok := ret.Get(0).(func(uint64) (service.OnlinePlayerInfo, bool)); ok {
		return rf(playerGUID)
	}
	if rf, ok := ret.Get(0).(func(uint64) service.OnlinePlayerInfo); ok {
		r0 = rf(playerGUID)
	} else {
		r0 = ret.Get(0).(service.OnlinePlayerInfo)
	}

	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(playerGUID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// HandleCharacterLoggedIn provides a mock function with given fields: payload
func (_m *OnlinePlayersCache) HandleCharacterLoggedIn(payload events.GWEventCharacterLoggedInPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for HandleCharacterLoggedIn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(events.GWEventCharacterLoggedInPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleCharacterLoggedOut provides a mock function with given fields: payload
func (_m *OnlinePlayersCache) HandleCharacterLoggedOut(payload events.GWEventCharacterLoggedOutPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for HandleCharacterLoggedOut")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(events.GWEventCharacterLoggedOutPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleCharactersUpdates provides a mock function with given fields: payload
func (_m *OnlinePlayersCache) HandleCharactersUpdates(payload events.GWEventCharactersUpdatesPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for HandleCharactersUpdates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(events.GWEventCharactersUpdatesPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlayerLoggedIn provides a mock function with given fields: playerGUID, level, class, area
func (_m *OnlinePlayersCache) PlayerLoggedIn(playerGUID uint64, level uint32, class uint32, area uint32) {
	_m.Called(playerGUID, level, class, area)
}

// PlayerLoggedOut provides a mock function with given fields: playerGUID
func (_m *OnlinePlayersCache) PlayerLoggedOut(playerGUID uint64) {
	_m.Called(playerGUID)
}

// SetFriendsService provides a mock function with given fields: friendsService
func (_m *OnlinePlayersCache) SetFriendsService(friendsService service.FriendsService) {
	_m.Called(friendsService)
}

// NewOnlinePlayersCache creates a new instance of OnlinePlayersCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOnlinePlayersCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *OnlinePlayersCache {
	mock := &OnlinePlayersCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
