// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	events "github.com/walkline/ToCloud9/shared/events"
)

// GroupServiceProducer is an autogenerated mock type for the GroupServiceProducer type
type GroupServiceProducer struct {
	mock.Mock
}

// ConvertedToRaid provides a mock function with given fields: payload
func (_m *GroupServiceProducer) ConvertedToRaid(payload *events.GroupEventGroupConvertedToRaidPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for ConvertedToRaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupConvertedToRaidPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupCreated provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupCreated(payload *events.GroupEventGroupCreatedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupCreatedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupDifficultyChanged provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupDifficultyChanged(payload *events.GroupEventGroupDifficultyChangedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupDifficultyChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupDifficultyChangedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupDisband provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupDisband(payload *events.GroupEventGroupDisbandPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupDisband")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupDisbandPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupInstanceBindExtensionRequest provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupInstanceBindExtensionRequest(payload *events.GroupEventInstanceBindExtensionRequestPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupInstanceBindExtensionRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventInstanceBindExtensionRequestPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupInstanceResetRequest provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupInstanceResetRequest(payload *events.GroupEventInstanceResetRequestPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupInstanceResetRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventInstanceResetRequestPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupMemberFlagsChanged provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupMemberFlagsChanged(payload *events.GroupEventMemberFlagsChangedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupMemberFlagsChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventMemberFlagsChangedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupMemberLeft provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupMemberLeft(payload *events.GroupEventGroupMemberLeftPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupMemberLeft")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupMemberLeftPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupMemberOnlineStatusChanged provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupMemberOnlineStatusChanged(payload *events.GroupEventGroupMemberOnlineStatusChangedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupMemberOnlineStatusChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupMemberOnlineStatusChangedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupMemberStateChanged provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupMemberStateChanged(payload *events.GroupEventMemberStateChangedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupMemberStateChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventMemberStateChangedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupMemberSubGroupChanged provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupMemberSubGroupChanged(payload *events.GroupEventMemberSubGroupChangedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupMemberSubGroupChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventMemberSubGroupChangedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupReadyCheckFinished provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupReadyCheckFinished(payload *events.GroupEventReadyCheckFinishedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupReadyCheckFinished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventReadyCheckFinishedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupReadyCheckMemberState provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupReadyCheckMemberState(payload *events.GroupEventReadyCheckMemberStatePayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupReadyCheckMemberState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventReadyCheckMemberStatePayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GroupReadyCheckStarted provides a mock function with given fields: payload
func (_m *GroupServiceProducer) GroupReadyCheckStarted(payload *events.GroupEventReadyCheckStartedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GroupReadyCheckStarted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventReadyCheckStartedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteCreated provides a mock function with given fields: payload
func (_m *GroupServiceProducer) InviteCreated(payload *events.GroupEventInviteCreatedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for InviteCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventInviteCreatedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaderChanged provides a mock function with given fields: payload
func (_m *GroupServiceProducer) LeaderChanged(payload *events.GroupEventGroupLeaderChangedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for LeaderChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupLeaderChangedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LootTypeChanged provides a mock function with given fields: payload
func (_m *GroupServiceProducer) LootTypeChanged(payload *events.GroupEventGroupLootTypeChangedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for LootTypeChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupLootTypeChangedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberAdded provides a mock function with given fields: payload
func (_m *GroupServiceProducer) MemberAdded(payload *events.GroupEventGroupMemberAddedPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for MemberAdded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventGroupMemberAddedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendChatMessage provides a mock function with given fields: payload
func (_m *GroupServiceProducer) SendChatMessage(payload *events.GroupEventNewMessagePayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for SendChatMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventNewMessagePayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TargetIconUpdated provides a mock function with given fields: payload
func (_m *GroupServiceProducer) TargetIconUpdated(payload *events.GroupEventNewTargetIconPayload) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for TargetIconUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.GroupEventNewTargetIconPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGroupServiceProducer creates a new instance of GroupServiceProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupServiceProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupServiceProducer {
	mock := &GroupServiceProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
